module.exports = {
    it: {
        translation: {
            POSITIVE_SOUND: `<audio src='soundbank://soundlibrary/ui/gameshow/amzn_ui_sfx_gameshow_positive_response_02'/> `,
            GREETING_SPEECHCON: `<say-as interpret-as="interjection">hip hip hurrà</say-as> `,
            DOUBT_SPEECHCON: `<say-as interpret-as="interjection">hmm</say-as> `,
            WELCOME_MSG: `Benvenuto in Memoria Amica, vorrei aiutare le persone che soffrono di deficit cognitivo, permettendo loro di gestire la propria vita nell’ambiente domestico. Ricorda, io non sono un medico, ma cercherò di aiutarti giorno per giorno. Se non sai cosa fare puoi chiedermi aiuto in qualsiasi momento! `,
            WELCOME_BACK_MSG: 'Ciao di nuovo, {{name}}! ',
            DAYS_LEFT_MSG: `Manca un giorno `,
            DAYS_LEFT_MSG_plural: 'Mancano {{count}} giorni ',
            WILL_TURN_MSG: `a quando farai un anno. `,
            WILL_TURN_MSG_plural: ` a quando farai {{count}} anni. `,
            BIRTHDATE: 'La tua data di nascita è : ',
            GREET_MSG: `$t(POSITIVE_SOUND) $t(GREETING_SPEECHCON) {{name}}. `,
            NOW_TURN_MSG: `Hai compiuto un anno `,
            NOW_TURN_MSG_plural: `Hai compiuto {{count}} anni! `,
            MISSING_MSG: `Non mi hai ancora detto di più su di te, vorrei delle informazioni per poterti aiutare a ricordarle in futuro. `,
            POST_SAY_HELP_MSG: `Posso aiutarti per altro? Cosa vorresti fare? `,
            PRE_HELP_MSG: `Come vuoi procedere? `,
            HELP_MSG: 'Possiamo creare dei timers o un nuovo promemoria, posso ricordarti qualsiasi cosa. Inoltre, puoi chiedermi quanti figli hai, quali sono i loro nomi e qual\'è il tuo contatto di emergenza. Se vuoi esercitare la memoria possiamo fare due giochi, se vuoi iniziare puoi dirmi: giochiamo con il primo gioco, oppure giochiamo con il secondo gioco. Vuoi sapere cos\' altro puoi fare? ',
            HELP_MSG2: 'Posso spiegarti cosa sono il declino cognitivo e la demenza, quali sono i primi sintomi e darti consigli per rilassarti, favorire il tuo benessere, per mangiare sano e per attività che potresti svolgere. Inoltre, posso ricordarti quando è il tuo compleanno e dirti tra quanti giorni compi gli anni, quale è il tuo numero di cellulare, dove abiti e la tua email. Infine, se stai uscendo puoi dirmelo così ti aiuterò. Cosa vuoi fare? ',
            DEMENTIA: 'Circa la metà delle persone che soffrono di deficit cognitivo lieve sviluppa demenza entro 3 anni. I sintomi includono solitamente perdita di memoria, problemi con il linguaggio e lo svolgimento di attività, cambiamenti di personalità, disorientamento e comportamenti anomali. Il trattamento si concentra sul mantenimento della funzione mentale il più a lungo possibile e sul sostegno fornito da parenti e terapisti. Trattare i disturbi che contribuiscono al peggioramento della demenza può a volte rallentare il declino mentale. Può essere molto utile creare un ambiente sicuro e di sostegno e alcuni farmaci possono aiutare per un po’. La persona che soffre di demenza, i familiari, altri assistenti e gli operatori sanitari implicati devono discutere e decidere la migliore strategia per tale situazione ed eventuali esercizi da associare alla terapia medica. è importante affrontare al meglio la vita quotidiana; posso darti consigli su come rilassarti e favorire il tuo benessere. ',
            RELAX:'Dedicare del tempo a prendersi cura di sè è di vitale importanza. Sia che ci si possa riposare tutto il giorno o solo per qualche minuto, si trae sempre beneficio a fare qualcosa che ci porta piacere. Un consiglio per rilassarsi è di concedersi del tempo, in base a quello a propria disposizione. Posso spiegarti come favorire una sana alimentazione oppure darti consigli per attività che favoriscano il benessere. ',
            SUPPLY:'Le proteine favoriscono la crescita e la riparazione dei tessuti. I carboidrati e gli zuccheri forniscono energia; i grassi sono necessari per assorbire alcune vitamine e acidi grassi essenziali. Le fibre servono per una digestione sana. Le vitamine ed i minerali sono necessari per funzioni differenti, tra cui processi nell\'organismo come la riparazione dei tessuti, il rafforzamento delle osse e l\'assorbimento delle sostanze nutritive. ',
            ACTIVITY: 'L’attività fisica calma lo stress e può quindi aiutare a prevenire i problemi di sonno e comportamenti anomali, come agitazione e vagabondaggio. Aiuta, inoltre, anche a migliorare l’equilibrio e a mantenere cuore e polmoni in buona salute. Un’attività mentale continua, inclusi gli hobby, l’interesse per gli eventi attuali e la lettura, aiutano a restare vigile. Cerca di porti dei piccoli obiettivi giornalieri e di allenare corpo e mente. Se vuoi posso darti dei consigli su alcune attività che potresti svolgere. ' ,
            SONSNAMES: 'I nomi dei tuoi figli sono: ',
            EMERGENCYCONTACT: 'Il tuo contatto di emergenza è: ',
            REPROMPT_MSG: `Se non sai cosa fare, prova a chiedermi aiuto. Se vuoi uscire dimmi pure stop. Cosa vuoi fare? `,
            GOODBYE_MSG: ['A presto, {{name}}! ', 'Ciao {{name}}! ', 'Arrivederci {{name}}! ', 'A dopo {{name}}! '],
            REFLECTOR_MSG: 'Hai invocato l\'intento {{intent}} ',
            FALLBACK_MSG: 'Perdonami, penso di non aver capito bene. Riprova.',
            ERROR_MSG: 'Scusa, c\'è stato un errore. Riprova.',
            NO_TIMEZONE_MSG: 'Non ho potuto determinare il tuo fuso orario. Verifica la configurazione del tuo dispositivo, e riprova.',
            REMINDER_CREATED_MSG: '{{name}}, il promemoria è stato creato con successo. ',
            REMINDER_ERROR_MSG: 'Si è verificato un errore nel creare il promemoria',
            UNSUPPORTED_DEVICE_MSG: `Questa funzionalità non è disponibile su questo dispositivo. `,
            CANCEL_MSG: `Ok, annullato. `,
            NUMBER_AVAILABLE: 'Questo è il tuo numero di cellulare: ',
            EMAIL_AVAILABLE: 'Questo è il tuo indirizzo email: ',
            NO_ADDRESS: 'Sembra che tu non abbia inserito il tuo indirizzo nell app di Amazon Alexa. ',
            NO_EMAIL: 'Sembra che tu non abbia inserito il tuo indirizzo email nell app di Amazon Alexa. ',
            NO_NUMBER: 'Sembra che tu non abbia inserito il tuo numero di cellulare nell app di Amazon Alexa. ',
            ERROR_PROFILE: 'Si è verificato un errore con l\'API del profilo cliente Alexa. Si prega di riprovare. ',
            NOTIFY_MISSING_PERMISSIONS: 'Abilita le autorizzazioni del profilo cliente nell\'app Amazon Alexa. ',
            MISSING_PERMISSION_MSG: `Non mi ha ancora dato accesso a creare promemoria. Ti ho appena inviato una card alla tua app. `,
            MISSING_PERMISSION_MSG2: `Non mi ha ancora dato accesso ad utilizzare la tua posizione. Ti ho appena inviato una card alla tua app. `,
            MISSING_PERMISSION_MSG3: `Non mi ha ancora dato accesso ad utilizzare il tuo numero di cellulare. Ti ho appena inviato una card alla tua app. `,
            MISSING_PERMISSION_MSG4: `Non mi ha ancora dato accesso ad utilizzare la tua email. Ti ho appena inviato una card alla tua app. `,
            FIRST_GAME: 'Giochiamo insieme con la memoria linguistica! Ti dirò una lista di parole e dopo dovrai dirmele, se non le ricordi puoi chiedermi di ripeterle! ',
            SECOND_GAME: 'Giochiamo insieme esercitando la memoria semantica! Ti leggerò un tema sulla seconda guerra mondiale e poi potrai provare a rispondere a delle domande. Iniziamo! ',
            SECOND_GAME_INSTR: 'Ora ti porrò delle domande riguardanti il tema che ti ho appena letto! Se non ricordi la risposta puoi dirmi: non lo so!  ',
            SECOND_GAME_INSTR1: 'Continuo con la lettura del tema, vediamo insieme come terminò la seconda guerra mondiale! ',
            STORY1: ' La Seconda Guerra Mondiale iniziò nel 1939 e terminò nel 1945. Fu combattuta da Germania, Italia e Giappone,  che formavano il cosiddetto "Asse". Mentre Inghilterra, Francia, Stati Uniti e Russia erano i cosiddetti "Alleati".  La guerra fu vinta dagli Alleati e terminò nel 1945 dopo la resa del Giappone, in cui due città - Hiroshima e Nagasaki - furono distrutte dalla bomba atomica sganciata dagli Stati Uniti.  La guerra iniziò con l\'invasione della Polonia da parte della Germania di Hitler, il primo settembre del 1939.  Secondo il programma razzista del führer tedesco, ebrei e popolazioni slave dovevano essere annientati.  Invadere la Polonia serviva ad Hitler per aumentare lo "spazio vitale" dei tedeschi (cioè della razza ariana) e per ottenere quindi maggiori risorse, sfruttando il lavoro degli slavi e distruggendo la loro cultura.  ',
            STORY2: ' Francia ed Inghilterra, intuendo la minaccia del Nazismo, si mossero in aiuto del Paese aggredito. Ma questo non fermò affatto Hitler.  Solo nel 1940 l\'Italia rinunciò alla "non belligeranza", cioè a non partecipare al conflitto, e decise così di entrare in guerra al fianco dei tedeschi.  All\'epoca l\'Italia era governata da Benito Mussolini, un altro dittatore come Hitler e fondatore del partito fascista.  ',
            STORY3: ' Nel 1941 anche il Giappone si schierò dalla parte della Germania, attaccando un porto americano nelle isole del Pacifico, provocando così la reazione degli Stati Uniti, che entrarono anch\'essi in guerra.  Hitler nel frattempo aveva invaso anche l\'Unione Sovietica.  Stati Uniti, Francia, Inghilterra ed Unione Sovietica furono chiamati "Alleati" mentre Germania, Italia e Giappone (assieme ad altri) formarono l\'Asse: la Seconda Guerra Mondiale fu combattuta proprio da queste grandi potenze.  ',
            STORY4: ' La Russia, attaccata dalla Germania, riuscì a bloccare l\'avanzata tedesca,  permettendo agli Alleati di passare al contrattacco.  Difatti essi nel 1943 sbarcarono in Sicilia ed il re, spaventato, fece arrestare Mussolini e scappò con la sua famiglia da Roma a Bari.  L\'8 settembre un governo provvisorio firmò un armistizio, cioè la pace, con gli americani. Gli alleati, nel frattempo, partirono dalla Sicilia per risalire lungo tutta la Penisola.  ',
            STORY5: ' Intanto, Hitler aveva fatto liberare Mussolini che nel Nord Italia fondò la Repubblica di Salò,  (dal nome di una cittadina sul lago di Garda).  Nel 1943 era nata intanto la Resistenza italiana,  un movimento politico fondato dai partiti antifascisti.  Nella Repubblica di Salò iniziò così una sanguinosa guerra civile tra i Partigiani della Resistenza ed i fascisti aiutati dai nazisti.  ',
            STORY6: ' Tra il 21 ed il 25 aprile 1945, i Partigiani diedero il segnale di insurrezione generale ed una massa enorme di italiani del Nord occupò le fabbriche e scese nelle piazze.  Mussolini tentò di fuggire, ma fu riconosciuto e fucilato:  il 25 aprile si festeggia quindi il giorno della liberazione dal fascismo.  Agli inizi di maggio del 1945, i russi entrarono a Berlino ed Hitler si suicidò.  In Europa la guerra era finita, ma il Giappone voleva continuare a combattere.  Gli Stati Uniti decisero, allora, di sganciare su Hiroshima e Nagasaki la bomba atomica per porre fine al conflitto.  Le due città furono rase completamente al suolo ed il Giappone decise di arrendersi, il 2 settembre 1945.  La Seconda Guerra Mondiale era finalmente finita.  ',
            END_GAME: 'Complimenti, spero ti sia divertito! Abbiamo terminato! Se vuoi riascoltare il tema puoi dire che vuoi giocare al secondo gioco! ',
            FIRST_ANSWER: ' L\'Asse era composto da Germania, Italia e Giappone. ',
            SECOND_ANSWER: ' Gli Alleati erano composti da Inghilterra, Francia, Stati Uniti e Russia. ',
            THIRD_ANSWER: ' La Germania scatenò la guerra invadendo la Polonia. ',
            FOURTH_ANSWER: ' L\'Italia in quel periodo era governata da Benito Mussolini. ',
            FIFTH_ANSWER: ' Benito Mussolini fondò il partito Fascista. ',
            SIXTH_ANSWER: ' Il re di Sicilia fece arrestare Mussolini. ',
            SEVENTH_ANSWER: ' Hitler riuscì a far liberare Mussolini. ',
            EIGHTH_ANSWER: ' La resistenza italiana era formata dai Partigiani. ',
            NINTH_ANSWER: ' Mussolini venne fucilato, tentando la fuga. ',
            TENTH_ANSWER: ' Il 25 aprile si festeggia la liberazione dal fascismo. ',
            PERMISSIONS_CARD_MSG: 'Ti ho appena inviato una card all\'app Alexa per abilitare le autorizzazioni per i timer. Abilitalo e apri di nuovo la skill! A presto. ',
            TIMER_COUNT_MSG: 'Tu hai impostato {{count}} timer. ',
            TIMER_COUNT_MSG_plural: 'Tu hai impostato {{count}} timers. ',
            LAST_TIMER_MSG: 'Il tuo ultimo timer è {{status}}. ',
            NO_TIMER_MSG: `Non hai impostato un timer. Prova a dire: imposta un timer. `,
            ANNOUNCEMENT_LOCALE_MSG: 'it-IT',
            ANNOUNCEMENT_TIMER_TITLE_MSG:'il mio timer',
            ANNOUNCEMENT_TEXT_MSG: 'Quello era il tuo timer per {{tmessage}}. ',
            TASK_LOCALE_MSG: 'it-IT',
            VOICE_PERMISSION_ACCEPTED: 'Ora puoi impostare un timer dicendo, imposta un timer di, seguito dalla durata. ',
            VOICE_PERMISSION_DENIED: 'Non possiamo continuare se non dai il consenso alla creazione di timer nell\' app Alexa. Per favore riprova più tardi. ',
            VOICE_PERMISSION_ERROR: 'Si è verificato un errore durante l\'abilitazione delle autorizzazioni. Per favore riprova più tardi. ',
            CREATE_TIMER_OK_MSG: 'Il tuo timer è ora in esecuzione! Se vuoi controllarlo, dì, controlla il mio timer. Puoi anche metterlo in pausa dicendo: metti in pausa il mio timer, oppure cancellarlo dicendo: cancella il mio timer. ',
            CREATE_TIMER_ERROR_MSG: 'Impossibile creare il timer. Scusa! ',
            READ_TIMER_ERROR_MSG: 'Impossibile leggere lo stato del timer. Scusa! ',
            DELETE_TIMER_OK_MSG: 'Il tuo timer è stato cancellato! Se vuoi crearne un altro, dì, imposta un timer di, seguito dalla durata. ',
            DELETE_TIMER_ERROR_MSG: 'Impossibile eliminare il timer. Scusa! ',
            PAUSE_TIMER_OK_MSG: 'Il tuo timer è stato sospeso! Se vuoi riprenderlio, dì, riprendi il mio timer. ',
            PAUSE_TIMER_ERROR_MSG: 'Impossibile mettere in pausa i timer. Scusa! ',
            RESUME_TIMER_OK_MSG: 'Il tuo timer è stato ripristinato! Se vuoi metterlo in pausa, dì, metti in pausa il mio timer. ',
            RESUME_TIMER_ERROR_MSG: 'Impossibile riprendere i timer. Scusa! ',
            ON_TIMER_STATUS_MSG: ' in esecuzione',
            OFF_TIMER_STATUS_MSG: ' spento',
            PAUSED_TIMER_STATUS_MSG: ' in pausa'
       }
    }
}